name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64' (or 'aarch64')
          distribution: 'full' # or: 'minimal' (but you probably don't want 'minimal', see note at the bottom of this doc)
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.9'       # or: 'stable' for the latest version, 'current'

      - name: Run a multi-line script
        run: raco test test/

